- name: kernel | reboot
  reboot:
    msg:               "reboot initiated by ansible"
    connect_timeout:   5
    reboot_timeout:    300
    pre_reboot_delay:  0
    post_reboot_delay: 0
    test_command:      uptime
  when: _reboot
